[2025-03-16T03:34:00.254+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-16T03:34:00.268+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.bronze_layer_group.quality_check_raw_data manual__2025-03-16T03:31:44.056845+00:00 [queued]>
[2025-03-16T03:34:00.275+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.bronze_layer_group.quality_check_raw_data manual__2025-03-16T03:31:44.056845+00:00 [queued]>
[2025-03-16T03:34:00.275+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-03-16T03:34:00.286+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): bronze_layer_group.quality_check_raw_data> on 2025-03-16 03:31:44.056845+00:00
[2025-03-16T03:34:00.294+0000] {standard_task_runner.py:72} INFO - Started process 1746 to run task
[2025-03-16T03:34:00.298+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'bronze_layer_group.quality_check_raw_data', 'manual__2025-03-16T03:31:44.056845+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpu6rtgp73']
[2025-03-16T03:34:00.300+0000] {standard_task_runner.py:105} INFO - Job 85: Subtask bronze_layer_group.quality_check_raw_data
[2025-03-16T03:34:00.351+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.bronze_layer_group.quality_check_raw_data manual__2025-03-16T03:31:44.056845+00:00 [running]> on host 3174348cc1e9
[2025-03-16T03:34:00.425+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='bronze_layer_group.quality_check_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T03:31:44.056845+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-16T03:31:44.056845+00:00'
[2025-03-16T03:34:00.426+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-16T03:34:00.430+0000] {log.py:232} WARNING - 2025-03-16 03:34:00.430 | INFO     | data_pipeline.bronze.validate_raw_data:validate_raw_data:171 - Initial columns: []
[2025-03-16T03:34:00.435+0000] {baseoperator.py:416} WARNING - GreatExpectationsOperator.execute cannot be called outside TaskInstance!
[2025-03-16T03:34:00.436+0000] {great_expectations.py:581} INFO - Running validation with Great Expectations...
[2025-03-16T03:34:00.436+0000] {great_expectations.py:583} INFO - Instantiating Data Context...
[2025-03-16T03:34:00.442+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/great_expectations/data_context/data_context/serializable_data_context.py:225: UserWarning: Warning. An existing `great_expectations.yml` was found here: /opt/***/include/gx.
    - No action was taken.
  warnings.warn(message)

[2025-03-16T03:34:00.493+0000] {file_data_context.py:222} INFO - FileDataContext loading fluent config
[2025-03-16T03:34:00.497+0000] {config.py:187} INFO - Loading 'datasources' ->
[]
[2025-03-16T03:34:00.595+0000] {great_expectations.py:599} INFO - Creating Checkpoint...
[2025-03-16T03:34:00.598+0000] {great_expectations.py:618} INFO - Running Checkpoint...
[2025-03-16T03:34:00.663+0000] {log.py:232} WARNING - 2025-03-16 03:34:00.614 | ERROR    | data_pipeline.bronze.validate_raw_data:validate_raw_data:241 - Failed to validate data
Traceback (most recent call last):

  File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
    |   |    -> <function main at 0x7f3383585430>
    |   -> <function Worker.__call__.<locals>.exit at 0x7f337f6d9e50>
    -> <module 'sys' (built-in)>
  File "/home/***/.local/lib/python3.9/site-packages/***/__main__.py", line 62, in main
    args.func(args)
    |    |    -> Namespace(subcommand='worker', autoscale=None, celery_hostname=None, concurrency=16, daemon=False, log_file=None, pid=None, q...
    |    -> <function lazy_load_command.<locals>.command at 0x7f338344a790>
    -> Namespace(subcommand='worker', autoscale=None, celery_hostname=None, concurrency=16, daemon=False, log_file=None, pid=None, q...
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           |     |       -> {}
           |     -> (Namespace(subcommand='worker', autoscale=None, celery_hostname=None, concurrency=16, daemon=False, log_file=None, pid=None, ...
           -> <function _providers_configuration_loaded.<locals>.wrapper at 0x7f337fce7b80>
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           |  |       -> {}
           |  -> (Namespace(subcommand='worker', autoscale=None, celery_hostname=None, concurrency=16, daemon=False, log_file=None, pid=None, ...
           -> <function _providers_configuration_loaded.<locals>.wrapper at 0x7f337fce7a60>
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/cli/celery_command.py", line 61, in wrapper
    providers_configuration_loaded(func)(*args, **kwargs)
    |                              |      |       -> {}
    |                              |      -> (Namespace(subcommand='worker', autoscale=None, celery_hostname=None, concurrency=16, daemon=False, log_file=None, pid=None, ...
    |                              -> <function worker at 0x7f337fce7940>
    -> <function providers_configuration_loaded at 0x7f3385f5bb80>
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
           |     |       -> {}
           |     -> (Namespace(subcommand='worker', autoscale=None, celery_hostname=None, concurrency=16, daemon=False, log_file=None, pid=None, ...
           -> <function worker at 0x7f337fce7940>
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/cli/celery_command.py", line 234, in worker
    _run_command_with_daemon_option(
    -> <function _run_command_with_daemon_option at 0x7f3380057c10>
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/cli/celery_command.py", line 47, in _run_command_with_daemon_option
    run_command_with_daemon_option(*args, **kwargs)
    |                               |       -> {'args': Namespace(subcommand='worker', autoscale=None, celery_hostname=None, concurrency=16, daemon=False, log_file=None, pi...
    |                               -> ()
    -> <function run_command_with_daemon_option at 0x7f337f3c3dc0>
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
    callback()
    -> <function worker.<locals>.run_celery_worker at 0x7f337f3ff040>
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/cli/celery_command.py", line 227, in run_celery_worker
    celery_app.worker_main(options)
    |          |           -> ['worker', '-O', 'fair', '--queues', 'default', '--concurrency', 16, '--hostname', None, '--loglevel', 'INFO', '--pool', 'pre...
    |          -> <function Celery.worker_main at 0x7f337fd354c0>
    -> <Celery ***.providers.celery.executors.celery_executor at 0x7f337f95b1f0>
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
    |    |          -> ['worker', '-O', 'fair', '--queues', 'default', '--concurrency', 16, '--hostname', None, '--loglevel', 'INFO', '--pool', 'pre...
    |    -> <function Celery.start at 0x7f337fd35430>
    -> <Celery ***.providers.celery.executors.celery_executor at 0x7f337f95b1f0>
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
    |      |         -> ['worker', '-O', 'fair', '--queues', 'default', '--concurrency', 16, '--hostname', None, '--loglevel', 'INFO', '--pool', 'pre...
    |      -> <function BaseCommand.main at 0x7f338250fd30>
    -> <DYMGroup celery>
  File "/home/***/.local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         |    |      -> <click.core.Context object at 0x7f337f39fca0>
         |    -> <function MultiCommand.invoke at 0x7f3382513d30>
         -> <DYMGroup celery>
  File "/home/***/.local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           |               |       |       |      -> <click.core.Context object at 0x7f337f39f9a0>
           |               |       |       -> <function Command.invoke at 0x7f3382513820>
           |               |       -> <CeleryDaemonCommand worker>
           |               -> <click.core.Context object at 0x7f337f39f9a0>
           -> <function MultiCommand.invoke.<locals>._process_result at 0x7f337f3c3790>
  File "/home/***/.local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           |   |      |    |           |   -> {'optimization': 'fair', 'queues': ['default'], 'concurrency': 16, 'hostname': 'celery@3174348cc1e9', 'loglevel': 20, 'pool':...
           |   |      |    |           -> <click.core.Context object at 0x7f337f39f9a0>
           |   |      |    -> <function worker at 0x7f337ec9cf70>
           |   |      -> <CeleryDaemonCommand worker>
           |   -> <function Context.invoke at 0x7f338250f5e0>
           -> <click.core.Context object at 0x7f337f39f9a0>
  File "/home/***/.local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       |       -> {'optimization': 'fair', 'queues': ['default'], 'concurrency': 16, 'hostname': 'celery@3174348cc1e9', 'loglevel': 20, 'pool':...
                       -> ()
  File "/home/***/.local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           | |                       |       -> {'optimization': 'fair', 'queues': ['default'], 'concurrency': 16, 'hostname': 'celery@3174348cc1e9', 'loglevel': 20, 'pool':...
           | |                       -> ()
           | -> <function get_current_context at 0x7f3382563160>
           -> <function worker at 0x7f337ec9cee0>
  File "/home/***/.local/lib/python3.9/site-packages/celery/bin/base.py", line 135, in caller
    return f(ctx, *args, **kwargs)
           | |     |       -> {'optimization': 'fair', 'queues': ['default'], 'concurrency': 16, 'hostname': 'celery@3174348cc1e9', 'loglevel': 20, 'pool':...
           | |     -> ()
           | -> <click.core.Context object at 0x7f337f39f9a0>
           -> <function worker at 0x7f337ec9ce50>
  File "/home/***/.local/lib/python3.9/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
    |      -> <function WorkController.start at 0x7f337f3728b0>
    -> <Worker: celery@3174348cc1e9 (running)>
  File "/home/***/.local/lib/python3.9/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
    |    |         |     -> <Worker: celery@3174348cc1e9 (running)>
    |    |         -> <function Blueprint.start at 0x7f337f33f040>
    |    -> <celery.worker.worker.WorkController.Blueprint object at 0x7f3355b0fd30>
    -> <Worker: celery@3174348cc1e9 (running)>
  File "/home/***/.local/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
    |    |     -> <Worker: celery@3174348cc1e9 (running)>
    |    -> <function StartStopStep.start at 0x7f337f340160>
    -> <step: Pool>
  File "/home/***/.local/lib/python3.9/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
           |    |   -> <function BasePool.start at 0x7f337f3ea670>
           |    -> <celery.concurrency.prefork.TaskPool object at 0x7f337b8fad30>
           -> <step: Pool>
  File "/home/***/.local/lib/python3.9/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
    |    -> <function TaskPool.on_start at 0x7f337f3c3820>
    -> <celery.concurrency.prefork.TaskPool object at 0x7f337b8fad30>
  File "/home/***/.local/lib/python3.9/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
        |    |       |              |    -> 16
        |    |       |              -> <celery.concurrency.prefork.TaskPool object at 0x7f337b8fad30>
        |    |       -> <class 'celery.concurrency.asynpool.AsynPool'>
        |    -> None
        -> <celery.concurrency.prefork.TaskPool object at 0x7f337b8fad30>
  File "/home/***/.local/lib/python3.9/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
                     |           |       -> {'initializer': <function process_initializer at 0x7f337f3ff430>, 'on_process_exit': <function process_destructor at 0x7f337f...
                     |           -> ()
                     -> 16
  File "/home/***/.local/lib/python3.9/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
    |    |                      -> 14
    |    -> <function AsynPool._create_worker_process at 0x7f337f3c43a0>
    -> <celery.concurrency.asynpool.AsynPool object at 0x7f337bf94b50>
  File "/home/***/.local/lib/python3.9/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
                                          -> 14
  File "/home/***/.local/lib/python3.9/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
    | -> <function BaseProcess.start at 0x7f337fe12700>
    -> <ForkProcess(ForkPoolWorker-15, started daemon)>
  File "/home/***/.local/lib/python3.9/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
    |    |        |    |      -> <ForkProcess(ForkPoolWorker-15, started daemon)>
    |    |        |    -> <staticmethod object at 0x7f337fe15970>
    |    |        -> <ForkProcess(ForkPoolWorker-15, started daemon)>
    |    -> None
    -> <ForkProcess(ForkPoolWorker-15, started daemon)>
  File "/home/***/.local/lib/python3.9/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
           |     -> <ForkProcess(ForkPoolWorker-15, started daemon)>
           -> <class 'billiard.popen_fork.Popen'>
  File "/home/***/.local/lib/python3.9/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
    |    |       -> <ForkProcess(ForkPoolWorker-15, started daemon)>
    |    -> <function Popen._launch at 0x7f337f6ac1f0>
    -> <billiard.popen_fork.Popen object at 0x7f33559f80d0>
  File "/home/***/.local/lib/python3.9/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
           |           -> <function BaseProcess._bootstrap at 0x7f337fe183a0>
           -> <ForkProcess(ForkPoolWorker-15, started daemon)>
  File "/home/***/.local/lib/python3.9/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
    |    -> <function BaseProcess.run at 0x7f337fe12670>
    -> <ForkProcess(ForkPoolWorker-15, started daemon)>
  File "/home/***/.local/lib/python3.9/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
    |    |        |    |        |    -> {}
    |    |        |    |        -> <ForkProcess(ForkPoolWorker-15, started daemon)>
    |    |        |    -> ()
    |    |        -> <ForkProcess(ForkPoolWorker-15, started daemon)>
    |    -> <celery.concurrency.asynpool.Worker object at 0x7f33559f86a0>
    -> <ForkProcess(ForkPoolWorker-15, started daemon)>
  File "/home/***/.local/lib/python3.9/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
    |   |    |    |            -> 73
    |   |    |    -> <function Worker.workloop at 0x7f337f43baf0>
    |   |    -> <celery.concurrency.asynpool.Worker object at 0x7f33559f86a0>
    |   -> <function Worker.__call__.<locals>.exit at 0x7f337f6d9e50>
    -> <module 'sys' (built-in)>
  File "/home/***/.local/lib/python3.9/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
                    |              |    |       -> {}
                    |              |    -> ('***.providers.celery.executors.celery_executor_utils.execute_command', '08bbebb7-7b0a-4035-a99e-d485d60a73a3', {'lang':...
                    |              -> <function fast_trace_task at 0x7f337f3751f0>
                    -> <bound method Worker.prepare_result of <celery.concurrency.asynpool.Worker object at 0x7f33559f86a0>>
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/trace.py", line 651, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
                    |     -> '***.providers.celery.executors.celery_executor_utils.execute_command'
                    -> {'celery.chain': <@task: celery.chain of ***.providers.celery.executors.celery_executor at 0x7f337f95b1f0>, 'celery.starm...
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 |    |       -> {}
                 |    -> [['***', 'tasks', 'run', 'data_pipeline', 'bronze_layer_group.quality_check_raw_data', 'manual__2025-03-16T03:31:44.05684...
                 -> <@task: ***.providers.celery.executors.celery_executor_utils.execute_command of ***.providers.celery.executors.celery...
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           |    |    |       -> {}
           |    |    -> (['***', 'tasks', 'run', 'data_pipeline', 'bronze_layer_group.quality_check_raw_data', 'manual__2025-03-16T03:31:44.05684...
           |    -> <staticmethod object at 0x7f337e86f400>
           -> <@task: ***.providers.celery.executors.celery_executor_utils.execute_command of ***.providers.celery.executors.celery...
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 141, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
    |                |                -> '08bbebb7-7b0a-4035-a99e-d485d60a73a3'
    |                -> ['***', 'tasks', 'run', 'data_pipeline', 'bronze_layer_group.quality_check_raw_data', 'manual__2025-03-16T03:31:44.056845...
    -> <function _execute_in_fork at 0x7f337f4af820>
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 177, in _execute_in_fork
    args.func(args)
    |    |    -> Namespace(subcommand='run', dag_id='data_pipeline', task_id='bronze_layer_group.quality_check_raw_data', execution_date_or_ru...
    |    -> <function lazy_load_command.<locals>.command at 0x7f33834ad4c0>
    -> Namespace(subcommand='run', dag_id='data_pipeline', task_id='bronze_layer_group.quality_check_raw_data', execution_date_or_ru...
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           |     |       -> {}
           |     -> (Namespace(subcommand='run', dag_id='data_pipeline', task_id='bronze_layer_group.quality_check_raw_data', execution_date_or_r...
           -> <function task_run at 0x7f337b545a60>
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           |  |       -> {}
           |  -> (Namespace(subcommand='run', dag_id='data_pipeline', task_id='bronze_layer_group.quality_check_raw_data', execution_date_or_r...
           -> <function task_run at 0x7f337b5459d0>
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       |                            |     |     -> <TaskInstance: data_pipeline.bronze_layer_group.quality_check_raw_data manual__2025-03-16T03:31:44.056845+00:00 [running]>
                       |                            |     -> <DAG: data_pipeline>
                       |                            -> Namespace(subcommand='run', dag_id='data_pipeline', task_id='bronze_layer_group.quality_check_raw_data', execution_date_or_ru...
                       -> <function _run_task_by_selected_method at 0x7f337b545430>
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
           |                           |     -> <TaskInstance: data_pipeline.bronze_layer_group.quality_check_raw_data manual__2025-03-16T03:31:44.056845+00:00 [running]>
           |                           -> Namespace(subcommand='run', dag_id='data_pipeline', task_id='bronze_layer_group.quality_check_raw_data', execution_date_or_ru...
           -> <function _run_task_by_local_task_job at 0x7f337b545550>
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
          |           |          |                     |          -> <function LocalTaskJobRunner._execute at 0x7f337e8f4dc0>
          |           |          |                     -> <***.jobs.local_task_job_runner.LocalTaskJobRunner object at 0x7f331c280d30>
          |           |          -> <***.jobs.job.Job object at 0x7f331c2807f0>
          |           -> <***.jobs.local_task_job_runner.LocalTaskJobRunner object at 0x7f331c280d30>
          -> <function run_job at 0x7f3380682940>
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           |     |             |          -> {'job': <***.jobs.job.Job object at 0x7f331c2807f0>, 'execute_callable': <bound method LocalTaskJobRunner._execute of <ai...
           |     |             -> <sqlalchemy.orm.session.Session object at 0x7f331c280a60>
           |     -> ()
           -> <function run_job at 0x7f33806828b0>
  File "/home/***/.local/lib/python3.9/site-packages/***/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
           |           |                     -> <bound method LocalTaskJobRunner._execute of <***.jobs.local_task_job_runner.LocalTaskJobRunner object at 0x7f331c280d30>>
           |           -> <***.jobs.job.Job object at 0x7f331c2807f0>
           -> <function execute_job at 0x7f33806829d0>
  File "/home/***/.local/lib/python3.9/site-packages/***/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
          -> <bound method LocalTaskJobRunner._execute of <***.jobs.local_task_job_runner.LocalTaskJobRunner object at 0x7f331c280d30>>
  File "/home/***/.local/lib/python3.9/site-packages/***/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
    |    |           -> <function StandardTaskRunner.start at 0x7f331c2085e0>
    |    -> <***.task.task_runner.standard_task_runner.StandardTaskRunner object at 0x7f331c203910>
    -> <***.jobs.local_task_job_runner.LocalTaskJobRunner object at 0x7f331c280d30>
  File "/home/***/.local/lib/python3.9/site-packages/***/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
    |    |         |    -> <function StandardTaskRunner._start_by_fork at 0x7f331c208790>
    |    |         -> <***.task.task_runner.standard_task_runner.StandardTaskRunner object at 0x7f331c203910>
    |    -> None
    -> <***.task.task_runner.standard_task_runner.StandardTaskRunner object at 0x7f331c203910>
  File "/home/***/.local/lib/python3.9/site-packages/***/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          |    |    |         |    -> <DAG: data_pipeline>
          |    |    |         -> <***.task.task_runner.standard_task_runner.StandardTaskRunner object at 0x7f331c203910>
          |    |    -> Namespace(subcommand='run', dag_id='data_pipeline', task_id='bronze_layer_group.quality_check_raw_data', execution_date_or_ru...
          |    -> <function lazy_load_command.<locals>.command at 0x7f33834ad4c0>
          -> Namespace(subcommand='run', dag_id='data_pipeline', task_id='bronze_layer_group.quality_check_raw_data', execution_date_or_ru...
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           |     |       -> {'dag': <DAG: data_pipeline>}
           |     -> (Namespace(subcommand='run', dag_id='data_pipeline', task_id='bronze_layer_group.quality_check_raw_data', execution_date_or_r...
           -> <function task_run at 0x7f337b545a60>
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           |  |       -> {'dag': <DAG: data_pipeline>}
           |  -> (Namespace(subcommand='run', dag_id='data_pipeline', task_id='bronze_layer_group.quality_check_raw_data', execution_date_or_r...
           -> <function task_run at 0x7f337b5459d0>
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       |                            |     |     -> <TaskInstance: data_pipeline.bronze_layer_group.quality_check_raw_data manual__2025-03-16T03:31:44.056845+00:00 [running]>
                       |                            |     -> <DAG: data_pipeline>
                       |                            -> Namespace(subcommand='run', dag_id='data_pipeline', task_id='bronze_layer_group.quality_check_raw_data', execution_date_or_ru...
                       -> <function _run_task_by_selected_method at 0x7f337b545430>
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           |             |     -> <TaskInstance: data_pipeline.bronze_layer_group.quality_check_raw_data manual__2025-03-16T03:31:44.056845+00:00 [running]>
           |             -> Namespace(subcommand='run', dag_id='data_pipeline', task_id='bronze_layer_group.quality_check_raw_data', execution_date_or_ru...
           -> <function _run_raw_task at 0x7f337b5455e0>
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           |  -> <function TaskInstance._run_raw_task at 0x7f3380380280>
           -> <TaskInstance: data_pipeline.bronze_layer_group.quality_check_raw_data manual__2025-03-16T03:31:44.056845+00:00 [running]>
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           |     |             |          -> {'mark_success': False, 'job_id': '85', 'pool': None}
           |     |             -> <sqlalchemy.orm.session.Session object at 0x7f3361db5fa0>
           |     -> (<TaskInstance: data_pipeline.bronze_layer_group.quality_check_raw_data manual__2025-03-16T03:31:44.056845+00:00 [running]>,)
           -> <function TaskInstance._run_raw_task at 0x7f33803801f0>
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           -> <function _run_raw_task at 0x7f33804233a0>
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
    |            -> <function TaskInstance._execute_task_with_callbacks at 0x7f33803803a0>
    -> <class '***.models.taskinstance.TaskInstance'>
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             |    |             |        -> <Task(_PythonDecoratedOperator): bronze_layer_group.quality_check_raw_data>
             |    |             -> {'conf': <***.configuration.AirflowConfigParser object at 0x7f3386071c10>, 'dag': <DAG: data_pipeline>, 'dag_run': <DagRu...
             |    -> <function TaskInstance._execute_task at 0x7f3380380430>
             -> <TaskInstance: data_pipeline.bronze_layer_group.quality_check_raw_data manual__2025-03-16T03:31:44.056845+00:00 [running]>
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           |             |     |        -> <Task(_PythonDecoratedOperator): bronze_layer_group.quality_check_raw_data>
           |             |     -> {'conf': <***.configuration.AirflowConfigParser object at 0x7f3386071c10>, 'dag': <DAG: data_pipeline>, 'dag_run': <DagRu...
           |             -> <TaskInstance: data_pipeline.bronze_layer_group.quality_check_raw_data manual__2025-03-16T03:31:44.056845+00:00 [running]>
           -> <function _execute_task at 0x7f3380423c10>
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             |                         |          -> {'_PythonDecoratedOperator__sentinel': <object object at 0x7f33844972b0>}
             |                         -> {'conf': <***.configuration.AirflowConfigParser object at 0x7f3386071c10>, 'dag': <DAG: data_pipeline>, 'dag_run': <DagRu...
             -> <function _execute_task.<locals>._execute_callable at 0x7f3361ddeee0>
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           -> <class '***.utils.operator_helpers.ExecutionCallableRunner'>
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           |    |     |       -> {'context': {'conf': <***.configuration.AirflowConfigParser object at 0x7f3386071c10>, 'dag': <DAG: data_pipeline>, 'dag_...
           |    |     -> ()
           |    -> <bound method DecoratedOperator.execute of <Task(_PythonDecoratedOperator): bronze_layer_group.quality_check_raw_data>>
           -> <***.utils.operator_helpers.ExecutionCallableRunner object at 0x7f337b3a3a60>
  File "/home/***/.local/lib/python3.9/site-packages/***/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           |    |      |       -> {'context': {'conf': <***.configuration.AirflowConfigParser object at 0x7f3386071c10>, 'dag': <DAG: data_pipeline>, 'dag_...
           |    |      -> ()
           |    -> <Task(_PythonDecoratedOperator): bronze_layer_group.quality_check_raw_data>
           -> <function DecoratedOperator.execute at 0x7f336e13bdc0>
  File "/home/***/.local/lib/python3.9/site-packages/***/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                                   -> {'conf': <***.configuration.AirflowConfigParser object at 0x7f3386071c10>, 'dag': <DAG: data_pipeline>, 'dag_run': <DagRu...
  File "/home/***/.local/lib/python3.9/site-packages/***/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           |    |      |       -> {}
           |    |      -> ({'conf': <***.configuration.AirflowConfigParser object at 0x7f3386071c10>, 'dag': <DAG: data_pipeline>, 'dag_run': <DagR...
           |    -> <Task(_PythonDecoratedOperator): bronze_layer_group.quality_check_raw_data>
           -> <function PythonOperator.execute at 0x7f337e8481f0>
  File "/home/***/.local/lib/python3.9/site-packages/***/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   |    -> <function PythonOperator.execute_callable at 0x7f337e848310>
                   -> <Task(_PythonDecoratedOperator): bronze_layer_group.quality_check_raw_data>
  File "/home/***/.local/lib/python3.9/site-packages/***/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           |      |    |    |          |    -> {}
           |      |    |    |          -> <Task(_PythonDecoratedOperator): bronze_layer_group.quality_check_raw_data>
           |      |    |    -> ({'data': [], 'skipped_files': 2},)
           |      |    -> <Task(_PythonDecoratedOperator): bronze_layer_group.quality_check_raw_data>
           |      -> <function ExecutionCallableRunner.run at 0x7f3380481af0>
           -> <***.utils.operator_helpers.ExecutionCallableRunner object at 0x7f3361d3f9d0>
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           |    |     |       -> {}
           |    |     -> ({'data': [], 'skipped_files': 2},)
           |    -> <function validate_raw_data at 0x7f331c5e9dc0>
           -> <***.utils.operator_helpers.ExecutionCallableRunner object at 0x7f3361d3f9d0>

> File "/opt/***/dags/data_pipeline/bronze/validate_raw_data.py", line 218, in validate_raw_data
    validation_result = gx_validate.execute(context={})
                        |           -> <function GreatExpectationsOperator.execute at 0x7f331c5e9a60>
                        -> <Task(GreatExpectationsOperator): quality_check_raw_data>

  File "/home/***/.local/lib/python3.9/site-packages/***/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           |    |      |       -> {'context': {}}
           |    |      -> ()
           |    -> <Task(GreatExpectationsOperator): quality_check_raw_data>
           -> <function GreatExpectationsOperator.execute at 0x7f331c5e9940>
  File "/home/***/.local/lib/python3.9/site-packages/great_expectations_provider/operators/great_expectations.py", line 621, in execute
    result = self.checkpoint.run(batch_request=self.batch_request)
             |    |          |                 |    -> {
             |    |          |                 |         "datasource_name": "nyc_taxi_data_asset_runtime_datasource",
             |    |          |                 |         "data_connector_name": "default_runtime_connector",
             |    |          |                 |         "dat...
             |    |          |                 -> <Task(GreatExpectationsOperator): quality_check_raw_data>
             |    |          -> <function BaseCheckpoint.run at 0x7f331cfca940>
             |    -> {
             |         "action_list": [
             |           {
             |             "name": "store_validation_result",
             |             "action": {
             |               "class_name": "StoreValidationR...
             -> <Task(GreatExpectationsOperator): quality_check_raw_data>
  File "/home/***/.local/lib/python3.9/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 266, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
             |     |       -> {'batch_request': {
             |     |            "datasource_name": "nyc_taxi_data_asset_runtime_datasource",
             |     |            "data_connector_name": "default_runtime_...
             |     -> ({
             |          "action_list": [
             |            {
             |              "name": "store_validation_result",
             |              "action": {
             |                "class_name": "StoreValidation...
             -> <function BaseCheckpoint.run at 0x7f331cfca9d0>
  File "/home/***/.local/lib/python3.9/site-packages/great_expectations/checkpoint/checkpoint.py", line 315, in run
    self._run_validation(
    |    -> <function BaseCheckpoint._run_validation at 0x7f331cfcaee0>
    -> {
         "action_list": [
           {
             "name": "store_validation_result",
             "action": {
               "class_name": "StoreValidationR...
  File "/home/***/.local/lib/python3.9/site-packages/great_expectations/checkpoint/checkpoint.py", line 480, in _run_validation
    validator: Validator = self._validator or self.data_context.get_validator(
                           |    |             |    -> <property object at 0x7f331cfce770>
                           |    |             -> {
                           |    |                  "action_list": [
                           |    |                    {
                           |    |                      "name": "store_validation_result",
                           |    |                      "action": {
                           |    |                        "class_name": "StoreValidationR...
                           |    -> None
                           -> {
                                "action_list": [
                                  {
                                    "name": "store_validation_result",
                                    "action": {
                                      "class_name": "StoreValidationR...
  File "/home/***/.local/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2338, in get_validator
    expectation_suite = self.get_expectation_suite(
                        |    -> <function AbstractDataContext.get_expectation_suite at 0x7f331cc8da60>
                        -> {
                             "anonymous_usage_statistics": {
                               "usage_statistics_url": "https://stats.greatexpectations.io/great_expectations/v1/usa...
  File "/home/***/.local/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 3035, in get_expectation_suite
    raise gx_exceptions.DataContextError(
          |             -> <class 'great_expectations.exceptions.exceptions.DataContextError'>
          -> <module 'great_expectations.exceptions' from '/home/***/.local/lib/python3.9/site-packages/great_expectations/exceptions/...

great_expectations.exceptions.exceptions.DataContextError: expectation_suite nyc_taxi_suite not found
[2025-03-16T03:34:00.665+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/data_pipeline/bronze/validate_raw_data.py", line 218, in validate_raw_data
    validation_result = gx_validate.execute(context={})
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/great_expectations_provider/operators/great_expectations.py", line 621, in execute
    result = self.checkpoint.run(batch_request=self.batch_request)
  File "/home/airflow/.local/lib/python3.9/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 266, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/great_expectations/checkpoint/checkpoint.py", line 315, in run
    self._run_validation(
  File "/home/airflow/.local/lib/python3.9/site-packages/great_expectations/checkpoint/checkpoint.py", line 480, in _run_validation
    validator: Validator = self._validator or self.data_context.get_validator(
  File "/home/airflow/.local/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2338, in get_validator
    expectation_suite = self.get_expectation_suite(
  File "/home/airflow/.local/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 3035, in get_expectation_suite
    raise gx_exceptions.DataContextError(
great_expectations.exceptions.exceptions.DataContextError: expectation_suite nyc_taxi_suite not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/data_pipeline/bronze/validate_raw_data.py", line 242, in validate_raw_data
    raise Exception(f"Failed to validate data: {str(e)}")
Exception: Failed to validate data: expectation_suite nyc_taxi_suite not found
[2025-03-16T03:34:00.676+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline, task_id=bronze_layer_group.quality_check_raw_data, run_id=manual__2025-03-16T03:31:44.056845+00:00, execution_date=20250316T033144, start_date=20250316T033400, end_date=20250316T033400
[2025-03-16T03:34:00.690+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-16T03:34:00.690+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 85 for task bronze_layer_group.quality_check_raw_data (Failed to validate data: expectation_suite nyc_taxi_suite not found; 1746)
Traceback (most recent call last):
  File "/opt/airflow/dags/data_pipeline/bronze/validate_raw_data.py", line 218, in validate_raw_data
    validation_result = gx_validate.execute(context={})
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/great_expectations_provider/operators/great_expectations.py", line 621, in execute
    result = self.checkpoint.run(batch_request=self.batch_request)
  File "/home/airflow/.local/lib/python3.9/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 266, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/great_expectations/checkpoint/checkpoint.py", line 315, in run
    self._run_validation(
  File "/home/airflow/.local/lib/python3.9/site-packages/great_expectations/checkpoint/checkpoint.py", line 480, in _run_validation
    validator: Validator = self._validator or self.data_context.get_validator(
  File "/home/airflow/.local/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2338, in get_validator
    expectation_suite = self.get_expectation_suite(
  File "/home/airflow/.local/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 3035, in get_expectation_suite
    raise gx_exceptions.DataContextError(
great_expectations.exceptions.exceptions.DataContextError: expectation_suite nyc_taxi_suite not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/data_pipeline/bronze/validate_raw_data.py", line 242, in validate_raw_data
    raise Exception(f"Failed to validate data: {str(e)}")
Exception: Failed to validate data: expectation_suite nyc_taxi_suite not found
[2025-03-16T03:34:00.742+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-16T03:34:00.761+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-16T03:34:00.763+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
