[2025-02-16T08:10:22.117+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-16T08:10:22.131+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.bronze_layer_group.ingest_raw_data manual__2025-02-16T07:56:51.984084+00:00 [queued]>
[2025-02-16T08:10:22.141+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.bronze_layer_group.ingest_raw_data manual__2025-02-16T07:56:51.984084+00:00 [queued]>
[2025-02-16T08:10:22.141+0000] {taskinstance.py:2866} INFO - Starting attempt 4 of 4
[2025-02-16T08:10:22.152+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): bronze_layer_group.ingest_raw_data> on 2025-02-16 07:56:51.984084+00:00
[2025-02-16T08:10:22.160+0000] {standard_task_runner.py:72} INFO - Started process 514 to run task
[2025-02-16T08:10:22.164+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'bronze_layer_group.ingest_raw_data', 'manual__2025-02-16T07:56:51.984084+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmppm0pm871']
[2025-02-16T08:10:22.166+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask bronze_layer_group.ingest_raw_data
[2025-02-16T08:10:22.215+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.bronze_layer_group.ingest_raw_data manual__2025-02-16T07:56:51.984084+00:00 [running]> on host 2f1303a52b9d
[2025-02-16T08:10:22.294+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='bronze_layer_group.ingest_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T07:56:51.984084+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-16T07:56:51.984084+00:00'
[2025-02-16T08:10:22.295+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-16T08:10:22.298+0000] {ingest_raw_data.py:126} INFO - Scanning for files in topics/tracking.user_behavior.validated/year=2025/month=01...
[2025-02-16T08:10:22.299+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-02-16T08:10:22.301+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-16T08:10:22.301+0000] {warnings.py:109} WARNING - <string>:9: UserWarning: AWS Connection (conn_id='minio_conn', conn_type='s3') expected connection type 'aws', got 's3'. This connection might not work correctly. Please use Amazon Web Services Connection type.

[2025-02-16T08:10:22.302+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='s3') credentials retrieved from login and password.
[2025-02-16T08:10:22.855+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/data_pipeline/bronze/ingest_raw_data.py", line 127, in ingest_raw_data
    all_keys = get_all_keys_paginated(
  File "/opt/airflow/dags/data_pipeline/bronze/ingest_raw_data.py", line 99, in get_all_keys_paginated
    for page in paginator.paginate(Bucket=bucket_name, Prefix=prefix):
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/data_pipeline/bronze/ingest_raw_data.py", line 241, in ingest_raw_data
    raise Exception(f"Failed to load data from MinIO: {str(e)}")
Exception: Failed to load data from MinIO: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
[2025-02-16T08:10:22.862+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=data_pipeline, task_id=bronze_layer_group.ingest_raw_data, run_id=manual__2025-02-16T07:56:51.984084+00:00, execution_date=20250216T075651, start_date=20250216T081022, end_date=20250216T081022
[2025-02-16T08:10:22.872+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-16T08:10:22.873+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 22 for task bronze_layer_group.ingest_raw_data (Failed to load data from MinIO: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist; 514)
Traceback (most recent call last):
  File "/opt/airflow/dags/data_pipeline/bronze/ingest_raw_data.py", line 127, in ingest_raw_data
    all_keys = get_all_keys_paginated(
  File "/opt/airflow/dags/data_pipeline/bronze/ingest_raw_data.py", line 99, in get_all_keys_paginated
    for page in paginator.paginate(Bucket=bucket_name, Prefix=prefix):
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/data_pipeline/bronze/ingest_raw_data.py", line 241, in ingest_raw_data
    raise Exception(f"Failed to load data from MinIO: {str(e)}")
Exception: Failed to load data from MinIO: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
[2025-02-16T08:10:22.900+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-16T08:10:22.916+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-16T08:10:22.919+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
