[2025-03-16T03:53:03.975+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-16T03:53:03.989+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.bronze_layer_group.quality_check_raw_data manual__2025-03-16T03:48:17.725362+00:00 [queued]>
[2025-03-16T03:53:03.995+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.bronze_layer_group.quality_check_raw_data manual__2025-03-16T03:48:17.725362+00:00 [queued]>
[2025-03-16T03:53:03.995+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 5
[2025-03-16T03:53:04.005+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): bronze_layer_group.quality_check_raw_data> on 2025-03-16 03:48:17.725362+00:00
[2025-03-16T03:53:04.012+0000] {standard_task_runner.py:72} INFO - Started process 703 to run task
[2025-03-16T03:53:04.015+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'bronze_layer_group.quality_check_raw_data', 'manual__2025-03-16T03:48:17.725362+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpst894x2i']
[2025-03-16T03:53:04.016+0000] {standard_task_runner.py:105} INFO - Job 126: Subtask bronze_layer_group.quality_check_raw_data
[2025-03-16T03:53:04.057+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.bronze_layer_group.quality_check_raw_data manual__2025-03-16T03:48:17.725362+00:00 [running]> on host c891f3a5df31
[2025-03-16T03:53:04.132+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='bronze_layer_group.quality_check_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T03:48:17.725362+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-16T03:48:17.725362+00:00'
[2025-03-16T03:53:04.133+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-16T03:53:04.137+0000] {log.py:232} WARNING - 2025-03-16 03:53:04.136 | INFO     | data_pipeline.bronze.validate_raw_data:validate_raw_data:89 - Initial columns: []
[2025-03-16T03:53:04.140+0000] {baseoperator.py:416} WARNING - GreatExpectationsOperator.execute cannot be called outside TaskInstance!
[2025-03-16T03:53:04.141+0000] {great_expectations.py:581} INFO - Running validation with Great Expectations...
[2025-03-16T03:53:04.141+0000] {great_expectations.py:583} INFO - Instantiating Data Context...
[2025-03-16T03:53:04.264+0000] {file_data_context.py:222} INFO - FileDataContext loading fluent config
[2025-03-16T03:53:04.268+0000] {config.py:187} INFO - Loading 'datasources' ->
[]
[2025-03-16T03:53:04.375+0000] {great_expectations.py:599} INFO - Creating Checkpoint...
[2025-03-16T03:53:04.377+0000] {great_expectations.py:618} INFO - Running Checkpoint...
[2025-03-16T03:53:04.389+0000] {log.py:232} WARNING - 2025-03-16 03:53:04.389 | WARNING  | data_pipeline.bronze.validate_raw_data:validate_raw_data:139 - Great Expectations validation skipped: expectation_suite nyc_taxi_suite not found
[2025-03-16T03:53:04.392+0000] {monitoring.py:12} INFO - Pipeline Metrics:
[2025-03-16T03:53:04.393+0000] {monitoring.py:13} INFO - {
  "total_records": 0,
  "valid_records": 0,
  "invalid_records": 0,
  "validation_errors": {},
  "contains_dummy": false,
  "great_expectations_enabled": false
}
[2025-03-16T03:53:04.393+0000] {monitoring.py:39} WARNING - Pipeline Alerts:
Low data volume detected!
[2025-03-16T03:53:04.393+0000] {python.py:240} INFO - Done. Returned value was: {'data': [], 'metrics': {'total_records': 0, 'valid_records': 0, 'invalid_records': 0, 'validation_errors': {}, 'contains_dummy': False, 'great_expectations_enabled': False}}
[2025-03-16T03:53:04.414+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-16T03:53:04.415+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=bronze_layer_group.quality_check_raw_data, run_id=manual__2025-03-16T03:48:17.725362+00:00, execution_date=20250316T034817, start_date=20250316T035303, end_date=20250316T035304
[2025-03-16T03:53:04.470+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-16T03:53:04.494+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-16T03:53:04.496+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
