[2025-03-16T03:09:30.673+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-16T03:09:30.688+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.bronze_layer_group.ingest_raw_data manual__2025-03-16T03:09:22.227661+00:00 [queued]>
[2025-03-16T03:09:30.696+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.bronze_layer_group.ingest_raw_data manual__2025-03-16T03:09:22.227661+00:00 [queued]>
[2025-03-16T03:09:30.697+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-03-16T03:09:30.707+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): bronze_layer_group.ingest_raw_data> on 2025-03-16 03:09:22.227661+00:00
[2025-03-16T03:09:30.715+0000] {standard_task_runner.py:72} INFO - Started process 1129 to run task
[2025-03-16T03:09:30.720+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'bronze_layer_group.ingest_raw_data', 'manual__2025-03-16T03:09:22.227661+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpw8i2ci7b']
[2025-03-16T03:09:30.721+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask bronze_layer_group.ingest_raw_data
[2025-03-16T03:09:30.771+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.bronze_layer_group.ingest_raw_data manual__2025-03-16T03:09:22.227661+00:00 [running]> on host 3174348cc1e9
[2025-03-16T03:09:30.855+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='bronze_layer_group.ingest_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T03:09:22.227661+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-16T03:09:22.227661+00:00'
[2025-03-16T03:09:30.856+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-16T03:09:30.860+0000] {ingest_raw_data.py:132} INFO - Scanning for files in topics/tracking.user_behavior.validated/year=2025/month=01...
[2025-03-16T03:09:30.861+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-03-16T03:09:30.863+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-03-16T03:09:30.863+0000] {warnings.py:109} WARNING - <string>:9: UserWarning: AWS Connection (conn_id='minio_conn', conn_type='s3') expected connection type 'aws', got 's3'. This connection might not work correctly. Please use Amazon Web Services Connection type.

[2025-03-16T03:09:30.864+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='s3') credentials retrieved from login and password.
[2025-03-16T03:09:31.356+0000] {ingest_raw_data.py:143} INFO - Loading checkpoint data...
[2025-03-16T03:09:31.604+0000] {log.py:232} WARNING - 2025-03-16 03:09:31.604 | WARNING  | data_pipeline.bronze.ingest_raw_data:load_checkpoint:45 - No checkpoint found or error loading checkpoint: An error occurred (404) when calling the HeadObject operation: Not Found
[2025-03-16T03:09:31.605+0000] {ingest_raw_data.py:150} INFO - Found 2 new files to process
[2025-03-16T03:09:31.605+0000] {ingest_raw_data.py:166} INFO - Processing chunk 1/1 (2 files)
[2025-03-16T03:09:31.615+0000] {log.py:232} WARNING - 2025-03-16 03:09:31.615 | INFO     | data_pipeline.bronze.ingest_raw_data:process_s3_object:77 - Processing file nyc-taxi-duration-prediction/green_tripdata_2024-04.parquet
[2025-03-16T03:09:31.617+0000] {log.py:232} WARNING - 2025-03-16 03:09:31.616 | INFO     | data_pipeline.bronze.ingest_raw_data:process_s3_object:77 - Processing file nyc-taxi-duration-prediction/green_tripdata_2024-03.parquet
[2025-03-16T03:09:31.617+0000] {log.py:232} WARNING - 2025-03-16 03:09:31.617 | ERROR    | data_pipeline.bronze.ingest_raw_data:process_s3_object:92 - Error processing file green_tripdata_2024-04.parquet: get_object() only accepts keyword arguments.
[2025-03-16T03:09:31.618+0000] {log.py:232} WARNING - 2025-03-16 03:09:31.617 | ERROR    | data_pipeline.bronze.ingest_raw_data:process_s3_object:92 - Error processing file green_tripdata_2024-03.parquet: get_object() only accepts keyword arguments.
[2025-03-16T03:09:31.618+0000] {ingest_raw_data.py:211} INFO - Chunk 1 completed in 0.01 seconds. Speed: 0.00 MB/s
[2025-03-16T03:09:31.619+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/data_pipeline/bronze/ingest_raw_data.py", line 226, in ingest_raw_data
    raise Exception("No valid JSON data found in any files")
Exception: No valid JSON data found in any files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/data_pipeline/bronze/ingest_raw_data.py", line 247, in ingest_raw_data
    raise Exception(f"Failed to load data from MinIO: {str(e)}")
Exception: Failed to load data from MinIO: No valid JSON data found in any files
[2025-03-16T03:09:31.628+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline, task_id=bronze_layer_group.ingest_raw_data, run_id=manual__2025-03-16T03:09:22.227661+00:00, execution_date=20250316T030922, start_date=20250316T030930, end_date=20250316T030931
[2025-03-16T03:09:31.645+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-16T03:09:31.645+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 72 for task bronze_layer_group.ingest_raw_data (Failed to load data from MinIO: No valid JSON data found in any files; 1129)
Traceback (most recent call last):
  File "/opt/airflow/dags/data_pipeline/bronze/ingest_raw_data.py", line 226, in ingest_raw_data
    raise Exception("No valid JSON data found in any files")
Exception: No valid JSON data found in any files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/data_pipeline/bronze/ingest_raw_data.py", line 247, in ingest_raw_data
    raise Exception(f"Failed to load data from MinIO: {str(e)}")
Exception: Failed to load data from MinIO: No valid JSON data found in any files
[2025-03-16T03:09:31.677+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-16T03:09:31.695+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-16T03:09:31.697+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
